# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.message_controller:
        class: AppBundle\Controller\MessagesController
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
